(function(){const c=document.createElement("div");c.id="reading-progress";document.body.appendChild(c);function e(){const e=window.innerHeight;const t=document.documentElement.scrollHeight;const o=window.pageYOffset||document.documentElement.scrollTop;const n=o/(t-e)*100;c.style.width=n+"%"}window.addEventListener("scroll",e);window.addEventListener("resize",e)})();(function(){const e=document.querySelectorAll("img[data-src]");const t=new IntersectionObserver((e,o)=>{e.forEach(e=>{if(e.isIntersecting){const t=e.target;t.classList.add("loading");t.src=t.dataset.src;t.onload=()=>{t.classList.remove("loading");t.classList.add("loaded")};o.unobserve(t)}})});e.forEach(e=>t.observe(e))})();(function(){const e=document.querySelectorAll(".scroll-animation");const t=new IntersectionObserver(e=>{e.forEach(e=>{if(e.isIntersecting){e.target.classList.add("active")}})},{threshold:.1});e.forEach(e=>t.observe(e))})();(function(){const e=document.querySelectorAll("#recent-posts > .recent-post-item");e.forEach((e,t)=>{e.setAttribute("data-index",t+1)})})();(function(){const e=document.querySelectorAll("figure.highlight");e.forEach(o=>{if(o.querySelector(".copy-btn"))return;const n=document.createElement("button");n.className="copy-btn";n.textContent="复制";n.onclick=function(){const e=o.querySelector(".code")||o.querySelector("pre");const t=e.innerText||e.textContent;navigator.clipboard.writeText(t).then(()=>{n.textContent="已复制!";setTimeout(()=>{n.textContent="复制"},2e3)})};const e=o.querySelector(".highlight-tools");if(e){e.appendChild(n)}})})();(function(){const e=document.querySelector("#post-meta");if(!e)return;const t=e.querySelector("[datetime]");if(!t)return;const o=new Date(t.getAttribute("datetime"));const n=new Date;const c=Math.floor((n-o)/(1e3*60*60*24));if(c>180){const i=document.createElement("div");i.className="post-updated";i.innerHTML=`<i class="fas fa-exclamation-triangle"></i>本文最后更新于 ${c} 天前，文章内容可能已过时。`;const r=document.querySelector("#article-container");if(r){r.insertBefore(i,r.firstChild)}}})();(function(){document.querySelectorAll('a[href^="#"]').forEach(e=>{e.addEventListener("click",function(e){const t=this.getAttribute("href");if(t==="#")return;const o=document.querySelector(t);if(o){e.preventDefault();o.scrollIntoView({behavior:"smooth",block:"start"})}})})})();(function(){const e=document.querySelectorAll('a[href^="http"]');e.forEach(e=>{if(!e.hostname.includes(window.location.hostname)){e.setAttribute("target","_blank");e.setAttribute("rel","noopener noreferrer")}})})();(function(){const e=document.querySelectorAll("#article-container img");e.forEach(o=>{o.style.cursor="zoom-in";o.onclick=function(){const e=document.createElement("div");e.style.cssText=`
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: rgba(0, 0, 0, 0.9);
        z-index: 99999;
        display: flex;
        align-items: center;
        justify-content: center;
        cursor: zoom-out;
      `;const t=o.cloneNode();t.style.cssText=`
        max-width: 90%;
        max-height: 90%;
        object-fit: contain;
        box-shadow: 0 0 30px rgba(255, 255, 255, 0.3);
      `;e.appendChild(t);document.body.appendChild(e);e.onclick=function(){document.body.removeChild(e)}}})})();(function(){const e=document.querySelector("#go-up");if(!e)return;window.addEventListener("scroll",()=>{if(window.pageYOffset>300){e.style.opacity="1";e.style.visibility="visible"}else{e.style.opacity="0";e.style.visibility="hidden"}});e.onclick=function(e){e.preventDefault();window.scrollTo({top:0,behavior:"smooth"})}})();(function(){console.log("%c Butterfly 主题魔改版 ","background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%); color: #fff; padding: 10px 20px; border-radius: 5px; font-size: 16px; font-weight: bold;");console.log("%c 欢迎来到我的博客！","color: #4facfe; font-size: 14px;")})();